-- Amorce du point d'entrée Hyprland — /usr/share/eschaton/hypr/hyprland.lua
--
-- Copiée dans ~/.config/hypr/hyprland.lua par /usr/bin/eschaton-session, au
-- PREMIER démarrage seulement (quand le fichier n'existe pas). Elle est ensuite
-- la propriété de DMS : un `dms setup` la régénère, en la sauvegardant dans
-- ~/.config/hypr/.dms-backups/<horodatage>/ — et c'est très bien, la version de
-- DMS est plus complète que celle-ci. Aucun défaut Eschaton ne vit ici : ils
-- s'accrochent par dms/binds-user.lua (spec Bureau §4.2), que `dms setup`
-- préserve, et que les deux versions de ce fichier chargent.
--
-- Le reste de l'arbre (dms/*.lua) est déployé par les sous-commandes
-- `dms setup colors|outputs|layout|cursor|binds|windowrules`, qui n'ont besoin
-- d'aucun privilège — contrairement au `dms setup` complet, qui exige sudo pour
-- ajouter l'utilisateur au groupe `input` et abandonne sans lui.

hl.config({ autogenerated = false })

-- Amorçage systemd, repris à l'identique du bloc DMS_STARTUP que `dms setup`
-- génère : hyprland-session.target (livré par eschaton-desktop-config, absent du
-- paquet hyprland) tire graphical-session.target, qui tire dms.service.
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
